<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_media5</name>
   <tag></tag>
   <elementGuidId>e5940f20-a65f-4a30-b049-b0ee02a578b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[4]/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rel.pad-t-sm.pad-b-sm.pad-l-sm.pad-r-sm.height-full.flex.flex-column.justify-between.bg-mint._3sQ6B</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rel pad-t-sm pad-b-sm pad-l-sm pad-r-sm height-full flex flex-column justify-between bg-mint  _3sQ6B</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UNLIMITED DATA PLANSSave more with Unlimited Your WaySM Pick the perfect unlimited plan for each family member. AT&amp;T may temporarily slow data speeds if the network is busy. Eligible AT&amp;T Unlimited Plans: Starter, Extra, and Elite.Learn more</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;_3cgwC pagehomepage rel&quot;]/div[@class=&quot;max-width-container undefined&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row flex-items-stretch&quot;]/div[@class=&quot;grid-col-4 mar-t-xs mar-b-xs&quot;]/div[@class=&quot;rel pad-t-sm pad-b-sm pad-l-sm pad-r-sm height-full flex flex-column justify-between bg-mint  _3sQ6B&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[4]/div/div/div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[2]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See details'])[2]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
