<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>metaimage</name>
   <tag></tag>
   <elementGuidId>4ea4d998-b1f7-4cbc-b03c-0b528359c888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/head/meta[11]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
