<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>metaURL</name>
   <tag></tag>
   <elementGuidId>8866ef9d-6843-4bd3-bc5a-0974f4a1b545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/head/meta[10]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
