<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title</name>
   <tag></tag>
   <elementGuidId>f0bcdc44-dd2c-4d19-bc2b-345016f7cd39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/head/title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
